# Generated by Django 5.1.1 on 2024-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='categoryId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
